server:
  port: 8090
dubbo:
  consumer:
    timeout: 60000
    retries: 1
    check: false
  application:
    name: dubbo-consumer
  protocol:
    name: dubbo
    port: 20881
  registry:
    protocol: dubbo-consumer-registry
    address: zookeeper://192.168.146.129:2181
#  monitor:
#    protocol: registry



#  devtools:
#    livereload:
#      port: 35971
#    restart:
#      enabled: true  #热部署
spring:
  redis:
    host: 192.168.146.129
    port: 6379
    password: mark123456
    database: 1
    connect-timeout: 10
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1
logging:
  level:
    org.springframework: warn
# JWT配置
jwt:
  # 密匙Key
  secret: JWTSecret,tcgl
  # HeaderKey
  tokenHeader: Authorization
  # Token前缀
  tokenPrefix: Bearer
  # 过期时间，单位秒
  expiration: 300
  # 刷新时间，单位天
  refreshTime: 7
  # 配置白名单（不需要认证）
  antMatchers: /login/**,/register/**,/static/**


