debug: true
server:
  port: 8090
dubbo:
  application:
    name: dubbo-consumer
#  protocal:
#    id: dubbo
#    name: dubbo
#    port: 20880
  registry:
    address: zookeeper://192.168.146.129:2181
    timeout: 30000
  monitor:
    protocol: registry
