server:
  port: 8089
debug: true
dubbo:
  application:
    name: dubbo-webservice
#  protocal:
#    id: dubbo
#    name: dubbo
#    port: 20880
  registry:
    address: zookeeper://192.168.146.129:2181
cxf:
  path: /service

