dubbo:
    application:
        name: dubbo-provider
    config-center:
        timeout: 400000
    monitor:
        protocol: registry
    protocal:
        id: dubbo
        name: dubbo
        port: 20880
    registry:
        address: zookeeper://8.131.76.172:2181
        protocol: dubbo-provider-registry
        timeout: 4000000
mybatis:
    mapper-locations: classpath:mapper/*.xml
mybatis-plus:
    configuration:
        cache-enabled: false
        jdbc-type-for-null: 'null'
        map-underscore-to-camel-case: true
    global-config:
        db-column-underline: true
        field-strategy: 2
        id-type: 0
        refresh-mapper: false
    mapper-locations: classpath:**/*Mapper.xml
server:
    port: 8084
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
            filters: stat
            initialSize: 1
            maxActive: 20
            maxOpenPreparedStatements: 20
            maxWait: 60000
            minEvictableIdleTimeMillis: 300000
            minIdle: 1
            poolPreparedStatements: true
            testOnBorrow: false
            testOnReturn: false
            testWhileIdle: true
            timeBetweenEvictionRunsMillis: 60000
            validationQuery: select '1'
        name: test
        password: 123456
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
        username: root
